server:
  port: 8888

spring:
  application:
    name: seckill-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ea9f263d-7146-4196-bb5b-6e25ba813517
        group: gp-dev
