server:
  port: 8888

spring:
  application:
    name: seckill-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # company namespace: ea9f263d-7146-4196-bb5b-6e25ba813517
        # home
        namespace: 1a7e295d-ae56-47b4-9fbd-903950e67c56
        group: gp-dev
