# idea vm option 中加入 -Dserver.port=8862 启动多个服务
server:
  port: 8861
#  undertow:
#    buffer-size: 1024
#    io-threads: 6
#    worker-threads: 40
#    direct-buffers: true

# buffer-size
# 配置会影响 buffer，这些 buffer 会用于服务器连接的 IO 操作,有点类似 netty 的池化内存管理
# 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
# io-threads
# 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
# 不要设置过大，如果过大，启动项目会报错：打开文件数过多
# CPU有几核，就填写几。
# worker-threads
# 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
# 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
# direct-buffers
# 是否分配的直接内存(NIO直接分配的堆外内存)

spring:
  redis:
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 10000
    port: 6379
    host: localhost
    timeout: 60s
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
        # namespace: ea9f263d-7146-4196-bb5b-6e25ba813517
        group: gp-dev
  application:
    name: seckill-server

#feign:
#  httpclient:
#    connection-timeout: 5000
#
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000

seckill:
  goods:
    # 商品库存 key
    stock-key: "sk:goods:stock:"
    # 预热商品 key
    info-key: "sk:goods:info:"

